#!/usr/bin/env bash

# This script zips your plugin to make it easy for you to install or share it.
# By Luiz Bills
# License: GPL v3

CURRENT_DIR="."
DIR="$(realpath $CURRENT_DIR)"
PLUGIN_NAME="$(basename $DIR)"
TMP_DIR="/tmp/wp-plugin/$PLUGIN_NAME"
DEST_DIR="wp-build"

clear >$(tty) # clear the terminal

mkdir -p "$(dirname $TMP_DIR)"
rm -rf $TMP_DIR
echo "Copying plugin files from $DIR ..."
cp -R $DIR $TMP_DIR
cd $TMP_DIR

# PHP syntax checker
if ! command -v php &> /dev/null
then
	echo "Checking PHP syntax..."
	find . -type f -name '*.php' ! -path './vendor/*' -print0 | while read -d $'\0' file
	do
		output=$(php -l "$file")
		if [ ! $? -eq 0 ];
		then
			#echo "$output"
			echo -e "\e[31mPHP Syntax Error!\e[0m"
			exit 1
		fi
	done
fi

# composer install
if [ -f 'composer.json' ];
then
	rm -rf ./vendor
	echo "Installing composer dependencies..."
	composer install --no-dev
fi

# npm install
if [ -f 'package.json' ];
then
	echo "Installing NPM dependencies..."
	npm install
fi

# delete some dev files
echo "Removing unwanted files"
rm -Rf .wordpress-org
rm -Rf .git
rm -Rf .github
rm -Rf tests
rm -Rf docs
rm -Rf scripts
rm -Rf node_modules
rm -f .gitattributes
rm -f .gitignore
rm -f .gitmodules
rm -f .travis.yml
rm -f package-lock.json
rm -f composer.lock
rm -f phpunit.xml
rm -f phpunit.xml.dist
rm -f README.md
rm -f .coveralls.yml
rm -f .editorconfig
rm -f CONTRIBUTING.md
rm -f .gitpod.dockerfile
rm -f .gitpod.yml
rm -f .prettierrc.json

# find and delete any zip files
find $TMP_DIR -name "*.zip" -type f -delete

# build the zip file
echo "Creating zip file..."
mkdir -p "$DIR/$DEST_DIR"
rm -rf "$DIR/$DEST_DIR/$PLUGIN_NAME.zip" # erase any old build
cd ..
zip -qr "$DIR/$DEST_DIR/$PLUGIN_NAME.zip" "$PLUGIN_NAME" #zip tmp dir

# erase tmp dir
rm -rf $TMP_DIR

echo "Zip file created in $DIR/$DEST_DIR/$PLUGIN_NAME.zip"
