#!/usr/bin/env node

import * as esbuild from 'esbuild';
import path from 'node:path';
import clc from 'cli-color';

const watch = process.argv.indexOf('--watch') >= 0;

const files = ['assets/js/form.js', 'assets/css/form.css'];

for (const file of files) {
    build(file);
}

async function build(entry) {
    const ext = path.extname(entry);
    const regex = new RegExp(ext + '$');
    esbuild
        .build({
            entryPoints: [entry],
            outfile: entry.replace(regex, '.min' + ext),
            bundle: true,
            minify: true,
        })
        .then((result) => {
            if (result.errors.length === 0) {
                console.log(clc.green(entry + ' OK!'));
            } else {
                console.log(entry + 'error: ' + result.errors[0]);
            }
        });
}
